[pytest]

pythonpath = src/scenarios/CacodemonRecognition/training_files

testpaths = src/tests/Python_scripts

addopts = --cov=envs --cov=active_vision_model_training --cov=baseline_model_training --cov=model_evaluation --cov-report=term-missing --cov-report=html --cov-config=.coveragerc